
name: aseprite

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build, leave empty for latest"
        required: false

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Clone Skia source & pull externals
        run: |
          git clone --depth 1 https://skia.googlesource.com/skia skia
          cd skia
          python tools/git-sync-deps
          
      - name: Download & extract Skia binaries
        run: |
          curl -L -o Skia-Windows-Release-x64.zip \
            https://storage.googleapis.com/skia-…/Skia-Windows-Release-x64.zip
          7z x Skia-Windows-Release-x64.zip -o skia/out/Release-x64
          
      - name: Configure & build Aseprite
        run: |
          cmake -G Ninja ^
            -DLAF_BACKEND=skia ^
            -DSKIA_DIR="%CD%\skia\out\Release-x64" ^
            -B build aseprite
          ninja -C build aseprite

      - name: Build
        id: build
        shell: cmd
        run: call build.cmd
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          path: github
          if-no-files-found: error
    
